[package]
name = "xorfiles"
version = "0.1.0"
authors = ["alexjago"]
edition = "2018"
description = "XOR files together... with Rust!"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
